In [1]:
import numpy as np
print(np.arange(1, 21).reshape(4, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [2]:
import numpy as np
m = np.random.randint(1, 101, (5, 5))
print(f"Matrix:\n{m}\nMin = {m.min()}\nMax = {m.max()}")

Matrix:
[[  6  58  32  60  36]
 [ 90   4  12  25  27]
 [ 27  94  82  33  71]
 [  9  31  14 100  82]
 [ 33  55  13  94  25]]
Min = 4
Max = 100


In [3]:
import numpy as np
a = np.arange(1, 11)
print(np.where(a % 2 == 0, 0, a))

[1 0 3 0 5 0 7 0 9 0]


In [4]:
import numpy as np
A, B = np.arange(1, 10).reshape(3, 3), np.arange(9, 0, -1).reshape(3, 3)
print(A @ B)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [5]:
import numpy as np
m = np.arange(1, 26).reshape(5, 5)
print(m[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [6]:
import numpy as np
m = np.arange(1, 17).reshape(4, 4)
print(f"Row Sum: {m.sum(1)}\nCol Sum: {m.sum(0)}")

Row Sum: [10 26 42 58]
Col Sum: [28 32 36 40]


In [7]:
import numpy as np
a = np.arange(1, 16)
print(a[a > 10])

[11 12 13 14 15]


In [8]:
import numpy as np
print(np.arange(1, 10).reshape(3, 3).T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
import numpy as np
a = np.random.rand(10)
print((a - a.min()) / (a.max() - a.min()))

[0.50127149 0.26329654 0.21620285 0.13477201 0.9002015  1.
 0.35310153 0.12268157 0.40597245 0.        ]


In [10]:
import numpy as np
print(np.arange(1, 11)[::-1])

[10  9  8  7  6  5  4  3  2  1]
